version: '3'
services:
  nginx:
    image: nginx:1.10
    container_name: chat-nginx
    links:
      - php-fpm
      - php-cli
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - php-cli
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    container_name: chat-php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    container_name: chat-php-cli
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    container_name: mysql_chat
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:$DB_PORT"
    env_file:
      - .env
    environment:
      - "MYSQL_ROOT_PASSWORD=$DB_PASSWORD"
      - "MYSQL_USER=$DB_USERNAME"
      - "MYSQL_PASSWORD=$DB_PASSWORD"
      - "MYSQL_DATABASE=$DB_DATABASE"

  redis:
    image: redis:3.0
    container_name: redis_chat
    ports:
      - "6379:6379"
  node:
    container_name: node
    build:
      context: ./
      dockerfile: docker/node.docker
    volumes:
      - ./:/var/www
    tty: true
